### ISSUE TITLE
TAP zombie

### ISSUE THREAD

**Issue by rolfinho** [tdmakepeace/pensando_tapasservice_docker#4]
If a mirror session is deleted in PSM, the TAP becomes a zombie TAP that can't be deleted and doesn't age out.

**Comment by tdmakepeace** [comment]
as a demo concept, the need to handle zombies is unnecessary at this time, will track to see interest first.

**Comment by tdmakepeace** [comment]
added code to handle and update the logs.

**Comment by tdmakepeace** [comment]
Added handle to deal with if some deletes off PSM.
