### ISSUE TITLE
Add more details to Filter/TAPs for user

### ISSUE THREAD

**Issue by rolfinho** [tdmakepeace/pensando_tapasservice_docker#5]
User can only see the name, would be good to have the option to see more details if he wants (maybe with a hoover option on the name?)

**Comment by tdmakepeace** [comment]
Option of a separate option where they can drill into the Target and workloads in read only mode is the easiest option.
Other option in once the tap is created and active, is to have a option to display the config on the active tap page, as it will always be a one to one.

**Comment by tdmakepeace** [comment]
Added view on active tap screen to see active tap details.
